### ISSUE TITLE
How to connect the power switch

### ISSUE THREAD

**Issue by tangbonze** [chadbailey59/CB70#1]
Could you please explain a little bit how to connect the power switch. I noticed that the switch on the PCB has two pins, but the switch has three pins. Thanks a lot.

**Comment by chadbailey59** [comment]
Sure! The simplest thing would be to use a single-pole, single-throw (SPST) switch, which only has two pins. In that case, you solder either pin to either terminal. The switch I mentioned is a single-pole, double-throw (SPDT) switch; I just snipped one of the outer legs to turn it into an SPST switch.
